spring:
  application:
    name: mail-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: mail-group-1

redis-url: localhost

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false