spring:
  application:
    name: post-service

  config:
    activate:
      on-profile: deploy

  kafka:
    consumer:
      bootstrap-servers: ${kafka_server_ip}
      group-id: ${kafka_group_id}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail_username}
    password: ${mail_password}

logging:
  file:
    path: /var/log/spring

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka_server_url}
  instance:
    prefer-ip-address: true
    ip-address: ${public_ip}

redis-url: ${redis_url}